"""3c Theme Generator — deterministic transformation (spec §5.1, Phase 1).

Pure, zero-LLM functions that turn (baseline + client extraction + 3b scoring)
into an in-memory customer-package tree. Fully deterministic: same inputs →
byte-identical output, so tests assert exact values (spec §7.3, SP-17).

The package is represented in memory as ``PackageTree = dict[relpath -> contents]``.
``write_package`` materialises it to disk; everything upstream stays FS-free so
unit tests need no temp dirs and stay fast + exact.

Deterministic vs agentic boundary (spec §5.3), implemented against the REAL 3b
``ScoringResult`` contract (NOT the spec's §3.2 sketch — see README "Rule-12
corrections"):

  * matched_via == "deterministic" AND deterministic_confidence in
    {authoritative, high}  → FORK the baseline component (deterministic).
  * matched_via == "no_candidates"                     → PASSTHROUGH (deterministic:
    no baseline equivalent, keep client's as-is; spec §5.1.4).
  * matched_via == "llm_required", or a deterministic match below high confidence
    → DEFER to Phase-2 agentic reconciliation. Phase 1 does NOT fabricate these;
    it records them in the provenance ledger and drops run status to "partial".

SP-9: no config/keys/URLs here. The package scope prefix is a caller-supplied
argument, never hardcoded.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Optional

from agents.theme_generator.models import (
    BlockingWarning,
    ComponentDerivation,
    ConfidenceSummary,
    ProvenanceSummary,
    UnmappedComponent,
)

PackageTree = dict[str, str]

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(name: str) -> str:
    """Lowercase, hyphen-collapsed slug. Deterministic; empty → 'customer'."""
    s = _SLUG_RE.sub("-", (name or "").strip().lower()).strip("-")
    return s or "customer"


def customer_package_name(customer_slug: str, scope: str) -> str:
    """``@{scope}/{slug}-elements`` (spec §4.3). ``scope`` is caller-supplied (SP-9)."""
    return f"@{scope}/{slugify(customer_slug)}-elements"


def render_package_json(customer_slug: str, scope: str, prov: ProvenanceSummary) -> str:
    """Deterministic package.json (spec §4.3). Sorted keys → byte-stable."""
    obj = {
        "name": customer_package_name(customer_slug, scope),
        "version": "0.1.0-3c-generated",
        "description": "Customer design system, forked from helix-code baseline",
        "type": "module",
        "provenance": {
            "baseline_source_ref": prov.baseline_source_ref,
            "baseline_cem_size_bytes": prov.baseline_cem_size_bytes,
            "generation_timestamp": prov.generation_timestamp,
            "engine_version": prov.engine_version,
        },
    }
    return json.dumps(obj, indent=2, sort_keys=True) + "\n"


def render_provenance_md(prov: ProvenanceSummary) -> str:
    """Customer-facing PROVENANCE.md (spec §4.4). Deterministic ordering."""
    cs = prov.confidence_summary
    lines = [
        "# PROVENANCE",
        "",
        "_Generated by the HELIX 3c Theme Generator. This package is a fork of the",
        "helix-code baseline with customer-specific modifications applied._",
        "",
        "## Baseline source",
        f"- Ref: `{prov.baseline_source_ref or 'unknown'}`",
        f"- CEM size: {prov.baseline_cem_size_bytes} bytes",
        f"- Generated: {prov.generation_timestamp or 'unstamped'}",
        f"- Engine: {prov.engine_version}",
        f"- Model routing (agent steps): {prov.model_routing or 'n/a (deterministic-only run)'}",
        "",
        "## Confidence summary",
        f"- authoritative: {cs.authoritative}",
        f"- high: {cs.high}",
        f"- medium: {cs.medium}",
        f"- unresolved: {cs.unresolved}",
        "",
        "## Component derivations",
    ]
    if prov.derivations:
        for d in prov.derivations:
            ref = f" (from `{d.baseline_ref}`)" if d.baseline_ref else ""
            reason = f" — {d.rationale}" if d.rationale else ""
            lines.append(f"- `{d.slot}`: {d.kind} [{d.confidence}]{ref}{reason}")
    else:
        lines.append("- (none)")
    lines.append("")
    return "\n".join(lines)


def _token_key(name: str) -> str:
    """Normalise a token name to a stable lookup key (strip leading dashes, lower)."""
    return (name or "").strip().lstrip("-").lower()


def substitute_tokens(baseline_tokens: list[dict], client_tokens: list[Any]) -> tuple[str, int]:
    """Overlay client token VALUES onto the baseline token set by name (spec §5.1.3).

    Deterministic: baseline order preserved; a client token with a matching
    (dash/case-insensitive) name overrides the baseline value, else the baseline
    default is kept. Returns (tokens.json string, substitution_count).
    """
    client_by_key = {}
    for t in client_tokens or []:
        name = getattr(t, "name", None) if not isinstance(t, dict) else t.get("name")
        value = getattr(t, "value", None) if not isinstance(t, dict) else t.get("value")
        if name:
            client_by_key[_token_key(name)] = value
    out: dict[str, Any] = {}
    subs = 0
    for bt in baseline_tokens or []:
        bname = bt.get("name") if isinstance(bt, dict) else getattr(bt, "name", None)
        bval = bt.get("value") if isinstance(bt, dict) else getattr(bt, "value", None)
        if not bname:
            continue
        k = _token_key(bname)
        if k in client_by_key and client_by_key[k] is not None:
            out[bname] = client_by_key[k]
            subs += 1
        else:
            out[bname] = bval
    return json.dumps(out, indent=2, sort_keys=True) + "\n", subs


def _element_module(slot: str, baseline_ref: Optional[str], kind: str) -> str:
    """A thin, deterministic element descriptor for the customer package.

    3c emits the fork intent (which baseline component + provenance); full
    framework code is 3d/3e's job (spec §1.3), so this stays a descriptor, not
    a component implementation.
    """
    origin = f"forked from baseline `{baseline_ref}`" if baseline_ref else "customer-defined (no baseline equivalent)"
    return (
        f"// {slot} — {origin}\n"
        f"// derivation: {kind}\n"
        f"// generated by HELIX 3c Theme Generator (deterministic path)\n"
        f"export const meta = {json.dumps({'slot': slot, 'baselineRef': baseline_ref, 'derivation': kind}, sort_keys=True)};\n"
    )


def _attr(obj: Any, name: str) -> Any:
    """Field access that works for both pydantic objects and plain dicts.

    3b returns ``ScoringResult`` objects in-process, but an Agno run carries the
    same shape as JSON dicts across step boundaries — so 3c reads both.
    """
    if isinstance(obj, dict):
        return obj.get(name)
    return getattr(obj, name, None)


def _det_confidence(scoring: Any) -> Optional[str]:
    return _attr(scoring, "deterministic_confidence")


def _matched_via(scoring: Any) -> Optional[str]:
    return _attr(scoring, "matched_via")


def _top_baseline_ref(scoring: Any) -> Optional[str]:
    cands = _attr(scoring, "top_candidates") or []
    if cands:
        return _attr(cands[0], "baseline_var")
    return None


def classify_component(scoring: Any) -> tuple[str, str]:
    """Map a 3b ScoringResult to (action, confidence) for the Phase-1 boundary.

    action ∈ {"fork", "passthrough", "defer"}. confidence is the 3c-level label.
    Real 3b enum: matched_via ∈ {deterministic, llm_required, no_candidates};
    deterministic_confidence ∈ {authoritative, high, None}.
    """
    via = _matched_via(scoring)
    conf = _det_confidence(scoring)
    if via == "deterministic" and conf in ("authoritative", "high"):
        return "fork", conf
    if via == "no_candidates":
        return "passthrough", "high"  # confident there is no baseline equivalent
    # llm_required, or deterministic-but-not-high → Phase-2 agent territory
    return "defer", "unresolved"


def build_deterministic_package(
    *,
    customer_slug: str,
    scope: str,
    baseline: dict,
    client_components: list[Any],
    scoring_by_slot: dict[str, Any],
    baseline_tokens: list[dict],
    client_tokens: list[Any],
    provenance: ProvenanceSummary,
) -> tuple[PackageTree, ProvenanceSummary, list[UnmappedComponent], list[BlockingWarning], str]:
    """Deterministic Step-2 transform (spec §5.1). Returns
    (tree, provenance, unmapped, blocking_warnings, status).

    status: "success" if every client component resolved deterministically;
    "partial" if any were deferred to Phase-2 agentic reconciliation;
    "failure" if inputs were empty (blocking_warning emitted, no package).
    """
    warnings: list[BlockingWarning] = []
    if not baseline:
        warnings.append(BlockingWarning(code="baseline_unavailable",
                                        detail="no baseline data provided", recommended_action="abort_run"))
    if not client_components:
        warnings.append(BlockingWarning(code="empty_client_extraction",
                                        detail="no client components to transform", recommended_action="abort_run"))
    if warnings:
        return {}, provenance, [], warnings, "failure"

    tree: PackageTree = {}
    derivations: list[ComponentDerivation] = []
    unmapped: list[UnmappedComponent] = []
    cs = ConfidenceSummary()
    deferred = 0

    # --- tokens (deterministic overlay) ---
    tokens_json, _subs = substitute_tokens(baseline_tokens, client_tokens)
    tree["src/tokens/tokens.json"] = tokens_json

    # --- components (stable order by slot name for byte-determinism) ---
    def _slot_name(c: Any) -> str:
        return (getattr(c, "name", None) if not isinstance(c, dict) else c.get("name")) or ""

    for comp in sorted(client_components, key=_slot_name):
        slot = _slot_name(comp)
        if not slot:
            continue
        scoring = scoring_by_slot.get(slot)
        action, conf = classify_component(scoring) if scoring is not None else ("defer", "unresolved")
        setattr(cs, conf, getattr(cs, conf) + 1)
        if action == "fork":
            ref = _top_baseline_ref(scoring)
            tree[f"src/elements/{slugify(slot)}.ts"] = _element_module(slot, ref, "forked_from_baseline")
            derivations.append(ComponentDerivation(slot=slot, kind="forked_from_baseline",
                                                    confidence=conf, baseline_ref=ref,
                                                    rationale="deterministic high-confidence match"))
        elif action == "passthrough":
            tree[f"src/elements/{slugify(slot)}.ts"] = _element_module(slot, None, "customer_passthrough")
            derivations.append(ComponentDerivation(slot=slot, kind="customer_passthrough",
                                                    confidence=conf,
                                                    rationale="no baseline candidate; kept client component as-is"))
            unmapped.append(UnmappedComponent(slot=slot, reason="no_candidates",
                                              detail="no baseline candidate; passthrough"))
        else:  # defer
            deferred += 1
            derivations.append(ComponentDerivation(slot=slot, kind="agent_flagged_review",
                                                    confidence="unresolved",
                                                    rationale="deferred to Phase-2 agentic reconciliation"))
            unmapped.append(UnmappedComponent(slot=slot, reason="llm_abstained",
                                              detail="requires agentic reconciliation (Phase 2)"))

    provenance.derivations = derivations
    provenance.confidence_summary = cs

    # --- static scaffolding + provenance docs (deterministic) ---
    tree["package.json"] = render_package_json(customer_slug, scope, provenance)
    tree["src/index.ts"] = "// customer design-system entry — exports generated by HELIX 3c\n"
    tree["docs/PROVENANCE.md"] = render_provenance_md(provenance)

    status = "partial" if deferred else "success"
    return tree, provenance, unmapped, warnings, status


def write_package(tree: PackageTree, dest: str | Path) -> str:
    """Materialise an in-memory PackageTree to ``dest``. Returns the dest path.

    Kept separate from the transform so the pure logic stays FS-free + testable.
    """
    root = Path(dest)
    for relpath, contents in tree.items():
        target = root / relpath
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(contents, encoding="utf-8")
    return str(root)
